apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: dev

spec:
  selector:
    matchLabels:
      app: node-agent

  template:
    metadata:
      labels:
        app: node-agent

    spec:
      containers:
        - name: node-agent
          image: busybox:1.36

          command:
            - sh
            - -c
            - |
              while true; do
                echo "Node agent is running"
                sleep 30
              done
