apiVersion: v1
kind: Pod
metadata:
  name: configmap-test
  namespace: dev
  labels:
    app: configmap-test
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_MESSAGE
